name: Deploy Shopee AI Assistant ke Firebase

on:
  push:
    # Workflow berjalan setiap kali kode di-push ke branch 'main'
    branches:
      - main
  # Mengizinkan menjalankan workflow ini secara manual
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4
      
      - name: Setup Node.js 20 # PASTIKAN INI BERLAKU
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      # Langkah 1: Instalasi Dependencies Functions (Backend)
      - name: Install Dependencies Functions
        run: |
          cd functions
          npm ci # Menginstal dependencies untuk backend (functions)
      
      # LANGKAH BARU: Build Kode Functions (khusus jika menggunakan TypeScript/bundler)
      - name: Build Firebase Functions
        run: |
          cd functions
          npm run build || true # Jalankan build, abaikan jika script tidak ada
      
      # Langkah 2: Deployment ke Firebase menggunakan Service Account Key JSON
      - name: Deploy ke Firebase Hosting and Functions
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # Menggunakan Service Account Key JSON yang tersimpan di Secret
          # Pastikan SECRET FIREBASE_SERVICE_ACCOUNT berisi seluruh konten JSON
          gcpCredentials: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' 
          channelId: live
          # GANTI 'YOUR_FIREBASE_PROJECT_ID' DENGAN ID PROYEK ASLI YANG ANDA TEMUKAN DI FIREBASE CONSOLE!
          projectId: assisten-shopee 
        env:
          # Variabel rahasia yang di-pass ke Firebase Functions
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
          SHOPEE_PARTNER_KEY: ${{ secrets.SHOPEE_PARTNER_KEY }} 
