name: Deploy Shopee AI Assistant ke Firebase

on:
  push:
    # workflow berjalan setiap kali kode di-push ke branch 'main'
    branches:
      - main
  # Mengizinkan menjalankan workflow ini secara manual
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Langkah 1: Instalasi Dependencies Functions (Backend)
      - name: Install Functions Dependencies (npm ci)
        run: |
          cd functions
          npm ci
        # Menginstal dependencies yang dibutuhkan oleh kode functions (index.js)
      
      # LANGKAH BUILD TELAH DIHAPUS KARENA TIDAK DIGUNAKAN DI JS MURNI.

      # Langkah 2: Deployment ke Firebase menggunakan Service Account Key JSON
      - name: Deploy ke Firebase Hosting and Functions
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' # Pastikan service account sudah diatur di secrets
          channelId: live
          projectId: assisten-shopee # HARUS DIGANTI DENGAN ID PROYEK ASLI ANDA!
        env:
          # Variabel rahasia yang di-pass ke Firebase Functions
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SHOPEE_PARTNER_KEY: ${{ secrets.SHOPEE_PARTNER_KEY }}
